// File generated by FlutterFire CLI & configured for the project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsSRQMUbzE2X4LNSfg8GRuIWUONELUYNM',
    appId: '1:1028194039722:android:23e2ea69d405c334165dd3',
    messagingSenderId: '1028194039722',
    projectId: 'e2-stories',
    storageBucket: 'e2-stories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSRQMUbzE2X4LNSfg8GRuIWUONELUYNM',
    appId: '1:1028194039722:ios:23e2ea69d405c334165dd3',
    messagingSenderId: '1028194039722',
    projectId: 'e2-stories',
    storageBucket: 'e2-stories.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSRQMUbzE2X4LNSfg8GRuIWUONELUYNM',
    appId: '1:1028194039722:web:23e2ea69d405c334165dd3',
    messagingSenderId: '1028194039722',
    projectId: 'e2-stories',
    storageBucket: 'e2-stories.firebasestorage.app',
  );
}
